logging:
  pattern:
    console: "[MSV Comm] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 1946
  
spring:
  application:
    name: msv-communication
  main:
    banner-mode: OFF
#  cloud:
#    consul:#      port: 1946
#      discovery:
#        instance-id: msv-communication-${random.int}
#        include-hostname-in-instance-id: true
#        prefer-ip-address: true

feign:
  circuitbreaker:    enabled: true
  client:
    config:
      payrollClient:
        retryer: com.danan.msvcommunication.api.client.FeignRetryer